### PR TITLE
Added HTTP basic auth w/ correct formatting

### PR DESCRIPTION
**Pull request by colebrumley**
Fix for #4

### CODE REVIEW

**Comment by EricR** [comment]
Small nitpick: The error should display "authentication is required" instead of "authorization is required", since it's using HTTP basic authentication. Other than that looks good to me!

**Comment by EricR** [comment]
I'm getting an error when I try setting the password "test" and making a request with the authorization header:

``` bash
go run sysjson.go modules.go -password "test" &
curl -H "Authorization: Basic dGVzdA==" http://localhost:5374/
```

```
2015/03/02 21:45:12 http: panic serving 127.0.0.1:35581: runtime error: index out of range
goroutine 24 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x67c980, 0x82351c)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
main.func·007(0x7f6b71e01a78, 0xc208052320, 0xc208000270)
        /home/eric/code/go/src/github.com/ericr/sys.json/src/sysjson.go:82 +0x3ba
net/http.HandlerFunc.ServeHTTP(0xc2080363c0, 0x7f6b71e01a78, 0xc208052320, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc208022450, 0x7f6b71e01a78, 0xc208052320, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080042a0, 0x7f6b71e01a78, 0xc208052320, 0xc208000270)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208050280)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by colebrumley** [comment]
My call is sending a user and password as the basic auth and yours is just sending the password.  I did it that way so that you could supply any username (or a blank) username and it would still work:

```
[root@sol src]# ./sysjson -password "test" -listen 0.0.0.0:5375
2015/03/02 22:09:10 [notice] sys.json listening on 0.0.0.0:5375

[root@sol ~]# curl -v -u anyuser:test http://localhost:5375
* About to connect() to localhost port 5375 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 5375 (#0)
* Server auth using Basic with user 'anyuser'
> GET / HTTP/1.1
> Authorization: Basic YW55dXNlcjp0ZXN0
> User-Agent: curl/7.29.0
> Host: localhost:5375
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 03 Mar 2015 03:24:15 GMT
< Content-Length: 175
<
* Connection #0 to host localhost left intact
{"current_time":{"string":"2015-03-02T22:24:15.799771858-05:00","unix":1425353055},"hostname":"sol.m3rl.in","modules_available":["net","load","uptime","process","mem","disk"]}
```

Let me add a little logic to sort that out.

**Comment by colebrumley** [comment]
OK, this should do it.  Tested working both ways:

```
[root@sol ~]# curl -v -H "Authorization: Basic dGVzdA==" http://localhost:5375/
* About to connect() to localhost port 5375 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 5375 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5375
> Accept: */*
> Authorization: Basic dGVzdA==
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 03 Mar 2015 03:44:14 GMT
< Content-Length: 175
<
* Connection #0 to host localhost left intact
{"current_time":{"string":"2015-03-02T22:44:14.822308451-05:00","unix":1425354254},"hostname":"sol.m3rl.in","modules_available":["disk","net","load","uptime","process","mem"]}

[root@sol ~]# curl -v -u anyuser:test http://localhost:5375
* About to connect() to localhost port 5375 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 5375 (#0)
* Server auth using Basic with user 'anyuser'
> GET / HTTP/1.1
> Authorization: Basic YW55dXNlcjp0ZXN0
> User-Agent: curl/7.29.0
> Host: localhost:5375
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 03 Mar 2015 03:48:45 GMT
< Content-Length: 175
<
* Connection #0 to host localhost left intact
{"current_time":{"string":"2015-03-02T22:48:45.175759571-05:00","unix":1425354525},"hostname":"sol.m3rl.in","modules_available":["disk","net","load","uptime","process","mem"]}
```

**Comment by EricR** [comment]
Nice! Looks good :+1:

**Pull request merged**
